name: LeeesExploitFixer
version: 2.0.1
main: Leees.Exploit.Fixer.Main
authors: [Leee and only Leee not skidded ;) nah jk mason made this all]
description: Prevent bullshit
commands:
  lefreload:
    description: reload config
  toggleconnectionmsgs:
    description: toggle join and leave messages
    usage: "toggleconnectionmsgs"
  elytrasound:
  mute:
  speed: