#LeeesExploitFixer ver 2.0.1
#this is the config for LeeesExploitFixer
#More shit to be added soon

IllegalBlock-Place:
  Bedrock: '&6That block is not allowed'
  Barrier: '&6That block is not allowed'
  End_Portal_Frame: '&6That block is not allowed'
  Mob_Spawner: '&6That block is not allowed'
ChunkBan:
  Prevent-Message: '&6ChunkBan has been disabled due to an exploit (^:'
  Skull-Max: 60
  TileEntity-Max: 256
Nether:
  Top-Layer: 127
  Top-message: '&6The nether top has been disabled due to lag'
  Bottom-Layer: 0
  Bottom-message: '&6The nether bottom has been disabled due to lag'
  top/bottom-do-damage: true
Spawn:
  Raidus: 1000
Offhand-Server-Crash:
  Shulker-messager: '&clel'
  Book-message: '&clel'