name: LeeesExploitFixer
version: 1.0.0
main: Leees.Protect.Main
authors: [Nate, Legault]
description: Leees Anti Backdoor
website: http://6b6t.org
commands:
  allowcreative:
    description: allows gmc